version: '3.3'

services:
  web:
    image: dockette/web:php-81
    volumes:
      - ./:/srv
    ports:
      - 80:80

    depends_on:
      - database

  database:
    restart: "always"
    image: mariadb:latest
    volumes:
      - my-database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysqlUser
      MYSQL_PASSWORD: toor
      MYSQL_DATABASE: allocation_system
      DB_HOST: 127.0.0.1

volumes:
  my-database:
